### ISSUE TITLE
User Story: Get LibriFox into the Firefox OS Marketplace

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#1]
I want to be able to install LibriFox from the Marketplace (Note: it would be great if you could confirm that the process described here: http://www.openbookproject.net/tutorials/fxos/episode04.html works, or get fixes to Aki if there are any that need to be made).

**Comment by ahirschberg** [comment]
It has been submitted, but hasn't been reviewed yet.  Also, because I think our old LibriFox app still exists in the market, I had to get the url marketplace.firefox.com/app/librifox-1/

**Comment by ahirschberg** [comment]
Should have closed this a while ago ;)
