### ISSUE TITLE
User Story: I want LibriFox to tell me I can't download when my phone is connected to my computer by USB.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#10]
If my phone is connected to my computer by USB, I can still start LibriFox and search for a book.  I can then click the "Download all chapters" link, it proceeds to attempt to download each part of the book, and then to fail at the end of each process.

I want it to tell me something like "You can't download books while your phone is connected by USB" instead.

**Comment by ahirschberg** [comment]
Fixed.
![image](https://cloud.githubusercontent.com/assets/5578698/9014715/32e7ae90-3792-11e5-8981-63aeb6ca8f2b.png)
