### ISSUE TITLE
User Story: I want to be able to tell LibriFox where to store my downloaded books.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#11]
I have a 32 Gig SD card in my phone, which has only 4 Gigs on its main storage to be shared among all apps.  Audio books are large, and I plan to store lots of them with LibriFox.  I want to be able to tell LibriFox where to store downloaded books.

**Comment by ahirschberg** [comment]
How would you like the existing downloaded files to be handled when the user switches from internal to external storage?  Should the files on the internal storage no longer show up, or should the app still show them, but save all files downloaded after the switch to the external storage?

**Comment by jelkner** [comment]
The download location should be stored in the app, and should be configurable. So different books could be stored on different available storage devices if the user changes location.

Yes, all books stored on all storage devices should be visible to the user.

**Comment by ahirschberg** [comment]
The storage device is now switchable from the settings page.  However, the UI still needs some work because it currently doesn't tell you which device you have selected.  I will close the issue once that is fixed.
