### ISSUE TITLE
Player sometimes misses next part when advancing through the parts of  a book.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#16]
I downloaded https://librivox.org/a-tale-of-two-cities-by-charles-dickens-2/ onto my phone and started playing it.  It played Bk1Ch01, Bk1Ch02, and then jumped to Bk1Ch04.  I stopped it, and returned to the last minute of Bk1Ch02.  This time it advanced to Bk1Ch03, but when that was finished it jumped to Bk1Ch05.

**Comment by ahirschberg** [comment]
After you started playing, but before it jumped to the wrong chapter, had you navigated around in the app? Or did you start it playing and it jumped to the wrong chapter without you doing any further interaction with the app? If you didn't pay attention to that, try to for next time it happens.  I'm suspicious that the player shortcut button in the index page may not always work correctly.  Thanks!

**Comment by ahirschberg** [comment]
I couldn't replicate the issue, but I've pushed changes that I think may have fixed the issue. Please let me know if it persists.

**Comment by jelkner** [comment]
I'll update the player at end of work today and try it out this evening.

**Comment by ahirschberg** [comment]
I haven't run into this issue at all in testing, and it's been 10 days, so I'm closing it.
