### ISSUE TITLE
LibriFox can't save downloaded books.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#17]
I updated LibriFox on my phone this morning, and attempted to download a book.  I got this error:

Error: could not write to file.
NoModificationAllowedError

**Comment by ahirschberg** [comment]
This error occurs when Librifox attempts to download a file but finds that the file is already present on the storage device.  I pushed a fix, but it's on the newid3 branch and probably won't hit master for a few more days.
