### ISSUE TITLE
Search comes up empty when it shouldn't.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#18]
I searched for "The Adventures of Maya the Bee" in LibriFox:

![librifox_book_not_found](https://cloud.githubusercontent.com/assets/819114/8873490/2df6f67e-31d5-11e5-8581-943538d6d735.png)

and the search came up empty, even though the same search on the LibriVox website returns the book:
![librivox_book_found](https://cloud.githubusercontent.com/assets/819114/8873512/586b3208-31d5-11e5-8be9-1910374d8b47.png)

**Comment by ahirschberg** [comment]
I looked into this issue, and it looks like the listing returned by their API cuts off the 'the' at the beginning.
![image](https://cloud.githubusercontent.com/assets/5578698/8985042/410e7048-36a3-11e5-9efe-664072fefc4d.png)

Looks like there are only four books in the LibriVox catalog that actually start with 'The '...

It might be worthwhile to warn the user when they search for a book starting with 'The'

**Comment by ahirschberg** [comment]
Added a helpful popup:
![image](https://cloud.githubusercontent.com/assets/5578698/8987050/0981132e-36ad-11e5-9119-9cf0574b2ccd.png)
