### ISSUE TITLE
Bug: Download progress bar jumps around radically

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#2]
I searched for "tale of two cities" and was offered several versions of the book (beginning for some reason with "Version 2").  When I clicked "Download all chapters" it downloaded the book, but instead of the progress bar increasing gradually from left to right, it flashed about spasmodically, apparently around a point that was making gradual progress from left to right.  It finally became solid when the book finished downloading.

**Comment by ahirschberg** [comment]
Resolved, clicking the download all chapters button now creates progress bars under each chapter's listing rather than updating all the progresses on one bar, which causes the spasms.  However, issue #6 still remains
