### ISSUE TITLE
User Story: I want the Chapters view to show my current section in a different background color.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#20]
LibriVox audio books can often be made up of a large number of small sections.  If a listener wants to return to a previous section, they click the return icon in the upper left of the screen to take them to the "Chapters" menu, and then click on the chapter to which they want to return.

It would be most helpful if the chapter they were viewing when they did this could be visually apparent in the Chapters menu.

**Comment by ahirschberg** [comment]
The state of the chapter is now shown next to it. There are four states:

(Look at chapter 05 / 06)
A play symbol represents that the chapter is being played by the player.
![image](https://cloud.githubusercontent.com/assets/5578698/9014629/97228002-3791-11e5-9e49-aa002a0ee334.png)

A pause symbol represents that the chapter was being played, but is currently paused.
![image](https://cloud.githubusercontent.com/assets/5578698/9014645/a903892e-3791-11e5-93b6-509ff6acc378.png)

An arrowhead represents that the chapter is not currently played or paused, but that it is the current chapter for that audiobook.
![image](https://cloud.githubusercontent.com/assets/5578698/9014660/beaffe60-3791-11e5-933a-cb0ab2e5bc6a.png)

And nothing next to a chapter means that none of these other three states apply.
![image](https://cloud.githubusercontent.com/assets/5578698/9014665/cbc705ee-3791-11e5-9b75-47fbd1b65089.png)
