### ISSUE TITLE
delete a book from the list

### ISSUE THREAD

**Issue by naugtur** [ahirschberg/LibriFox#23]
Add a feature to delete a book. 
Currently it's not even reasonable to delete a book from storage because names in fs are numbers.
I could contribute some if helped :)

**Comment by naugtur** [comment]
If user guesses the folder correctly all is fine. A minimal fix would be to append book name to the folder or put a file with book title inside if recursive delete is hard.

**Comment by ahirschberg** [comment]
Long pressing on a book list item now brings up a menu allowing you to delete the book

**Comment by naugtur** [comment]
doh. thanks!
