### ISSUE TITLE
Bug: Downloaded book files won't play.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#4]
I downloaded version two of "A Tale of Two Cities".  I can see the book in my list, and when I click on the book in the list I can see the list of book files.  When I click on any one of these, I see an audio player, but clicking the play button doesn't do anything other than change the play button to a pause button.

**Comment by ahirschberg** [comment]
I'm investigating this issue, but I haven't been able to replicate it.

What appears to have happened on your end is that the chapter's path reference stored in the JSON is incorrect, and so the player loads no audio.  Please check the developer console: in this case you should be getting an output that says DOMError { name: "NotFoundError" }.  Currently this error log doesn't output the path of the file trying to be loaded, but I will update that.

Try it again and see if you run into the same issue.
Thanks!

**Comment by ahirschberg** [comment]
Is this issue resolved? I'd like to close it.

**Comment by jelkner** [comment]
Go ahead and close it.
