### ISSUE TITLE
Bug: Won't save files to my phone.

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/LibriFox#9]
I just did a git pull on the current version (commit 8fd1d48701bbed0be8edec8a9eaa0fb71e322530), and deployed it to my phone.  Then I tried downloading Gulliver's Travels (https://librivox.org/gullivers-travels-by-jonathan-swift/).  As the progress bar finished for each file, I got the following error:
## LibriFox

failed to write file:
Unknown

I checked the phone's permissions for LibriFox, which are:

Memory Card Storage
Grant

**Comment by ahirschberg** [comment]
Make sure that you have gone into settings and disabled USB Storage (under the storage heading). While USB storage is enabled, LibriFox is not able to read or write to the sd card while your phone is plugged into your computer.

I was able to replicate your issue by connecting my phone to my computer, enabling USB storage and downloading the chapter 'Introduction' for Gulliver's Travels:
![unknown_error_mounted_sd](https://cloud.githubusercontent.com/assets/5578698/8426408/838e498a-1edd-11e5-862b-3a6ec501b98f.png)

**Comment by jelkner** [comment]
Yup, that's it.  I downloaded the book while my phone was not connected by USB and it worked fine.  I've filed a new Issue to cover that problem, so this one can be marked complete.
